### PR TITLE
Always BasicAPI last to prevent overriding when Raw at root is used

### PR DESCRIPTION
**Pull request by fizruk**
Having `Raw` for root is probably bad, however, it happens and in that case `Raw` should be last endpoint to check.

### CODE REVIEW

**Comment by phadej** [comment]
Sorry, I don't understand, where `Raw` is in the root? `SwaggerUI "ui" expands to `"ui" :> ...`: http://docs.futurice.com/haskell-mega-repo/servant-swagger-ui-0.1.0.2.1.4/Servant-Swagger-UI.html#t:SwaggerUI

**Comment by fizruk** [comment]
@phadej nowhere in those examples, but consider this one:

```haskell
-- if nothing works — serve files
type BasicAPI = ... :<|> Raw
```

If we place `SwaggerUI` or `SwaggerSchemaEndpoint` **after** `BasicAPI` in this example, we will get neither Swagger UI nor `swagger.js`. Moreover, it'll perfectly compile and you might not notice the problem until someone opens Swagger UI (which might not be very often).

Therefore I think we should recommend to place `BasicAPI` after both `SwaggerUI` and `SwaggerSchemaEndpoint`.

**Comment by phadej** [comment]
I see

**Comment by phadej** [comment]
Could you add a comment in the PR why we place `BasicAPI` at the end?

**Comment by fizruk** [comment]
I believe it's already there: https://github.com/phadej/servant-swagger-ui/pull/7/files#diff-b834628f4597c731be71950e773be335R39

**Comment by phadej** [comment]
great.

**Comment by phadej** [comment]
@fizruk released new version. Also added you as contributor (and maintainer on Hackage)

**Comment by fizruk** [comment]
Thanks!

**Pull request merged**
