### PR TITLE
Get nested URI for swagger.json

### LINKED ISSUE #8: Swagger UI does not work when nested
Example:

```haskell
type SwaggerSchemaEndpoint = "swagger.json" :> Get '[JSON] Swagger

type NestedAPIWithSwagger
     = SwaggerSchemaEndpoint
  :<|> SwaggerUI "docs" SwaggerSchemaEndpoint NestedApiPlaceholder
  :<|> NestedAPI

type API
    = "nested" :> NestedAPIWithSwagger
 :<|> Raw
```

This does not work since Swagger UI requests http://example.com/swagger.json and not http://example.com/nested/swagger.json

I have tried this:

```haskell
type NestedAPIWithSwagger
     = SwaggerSchemaEndpoint
  :<|> SwaggerUI "docs" ("nested" :> SwaggerSchemaEndpoint) NestedApiPlaceholder
  :<|> NestedAPI
```

but this results in a type error since `"nested" :> SwaggerSchemaEndpoint` is not part of `NestedAPIWithSwagger`.

I think we could fix `SwaggerUI` to request `swagger.json` relative to its root, since necessary information is available in the request. However I am not sure how hard it would be to implement.

### PR DESCRIPTION
**Pull request by fierce-katie**
Closes #8.

### CODE REVIEW

**Comment by fizruk** [comment]
Build fails due `-Werror`, this is fixed in #10.

This is a breaking change, since it directly modifies `SwaggerUiHtml`.
Specifically this will break when `SwaggerSchemaEndpoint` is not based where `SwaggerUI` is.

Documentation also needs an update.

@phadej what do you think?

**Comment by phadej** [comment]
Can we in introduce `type SwaggerUiHtml = SwaggerUiHtml' ""`, so the ones who doesn't face problem don't have to worry about it. Also less breaking change?

**Comment by fizruk** [comment]
Looks good to me. ping @phadej

**Comment by phadej** [comment]
So this makes assumption that `swagger.json` is in the same "root" as `ui`,
i.e. with

``hs
type SwaggerSchemaEndpoint = "swagger.json" :> Get '[JSON] Swagger

type BiggerAPI api =
    :<|> SwaggerSchemaEndpoint
    :<|> SwaggerUI "swagger-ui" SwaggerSchemaEndpoint (SwaggerSchemaEndpoint :<|> api)
```

this will work, as it strips the path until `swagger-ui` and looks for `swagger.json` there.

But with

```hs
type BiggerAPI' api =
    :<|> SwaggerSchemaEndpoint
    :<|> "dev" :> SwaggerUI "swagger-ui" SwaggerSchemaEndpoint (SwaggerSchemaEndpoint :<|> api)
```

it won't?

---

Of course latter case is contrived, but if the usage is always like first example (for me it is),
then I rather make the library less flexible to only allow

```
swagger.json
some-dir/<swagger-ui>
```

kind of layout:

```hs
type API' = SwaggerSchemaUI "swagger.json" "swagger-ui" API
    :<|> API
```

Would it be ok for you?

**Comment by fizruk** [comment]
Consider this example:

```haskell
type SecretSwaggerSchemaEndpoint
  = "secret" :> "swagger.json" :> Get '[JSON] Swagger

type PublicSwaggerSchemaEndpoint
  = "swagger.json" :> Get '[JSON] Swagger

type API'
    = SecretSwaggerSchemaEndpoint
 :<|> SwaggerUI "secret-docs" SecretSwaggerSchemaEndpoint ApiPlaceholder
 :<|> PublicSwaggerSchemaEndpoint
 :<|> SwaggerUI "docs" PublicSwaggerSchemaEndpoint ApiPlaceholder
 :<|> API
```

As you can see `/docs/` will serve Swagger UI for `/swagger.json`, while `/secret-docs/` will serve for `/secret/swagger.json`.

With `SwaggerSchemaUI "swagger.json" "swagger-ui" API` that would be impossible.

I, personally, don't use this kind of layout and would rather place secret docs under `/secret/docs/`:

```haskell
type API'
    = "secret" :> SwaggerSchemaUI "swagger.json" "docs" ApiPlaceholder
 :<|> SwaggerSchemaUI "swagger.json" "docs" ApiPlaceholder
 :<|> API
```

However, we could pass `SwaggerSchemaEndpoint` to `SwaggerSchemaUI`:

```haskell
type DefaultSwaggerSchemaEndpoint
  = "swagger.json" :> Get '[JSON] Swagger

type API'
    = SwaggerSchemaUI "secret-docs" ("secret" :> DefaultSwaggerSchemaEndpoint) ApiPlaceholder
 :<|> SwaggerSchemaUI "docs" DefaultSwaggerSchemaEndpoint ApiPlaceholder
 :<|> API
```

BTW, if you incorporate `swagger.json` into `SwaggerSchemaUI` then you don't need `ApiPlaceholder`, and it can be just:

```haskell
type API'
    = SwaggerSchemaUI "secret-docs" ("secret" :> DefaultSwaggerSchemaEndpoint)
 :<|> SwaggerSchemaUI "docs" DefaultSwaggerSchemaEndpoint
 :<|> API
```

Or even:

```haskell
-- | Endpoint, serving Swagger API spec as @swagger.json@.
type DefaultSwaggerSchemaEndpoint = "swagger.json" :> Get '[JSON] Swagger

-- | API, serving both Swagger UI and Swagger spec using 'DefaultSwaggerSchemaEndpoint'.
type DefaultSwaggerSchemaUI dir = SwaggerSchemaUI dir DegaultSwaggerSchemaEndpoint

type API'
 -- /secret-docs/      — Swagger UI
 -- /secret/swagger.js — Swagger spec
    = SwaggerSchemaUI "secret-docs" ("secret" :> "swagger.js" :> Get '[JSON] Swagger)
 -- /docs/             — Swagger UI
 -- /swagger.json      — Swagger spec
 :<|> DefaultSwaggerSchemaUI "docs"
 :<|> API
```

We could go further and generalize `dir` param as well:

```haskell
type API'
 -- /secret-docs/       — Swagger UI
 -- /secret/swagger.js  — Swagger spec
    = SwaggerUI ("secret-docs" :> SwaggerUI) ("secret" :> "swagger.js" :> Get '[JSON] Swagger)
 -- /docs/              — Swagger UI
 -- /swagger.json       — Swagger spec
 :<|> SwaggerSchemaUI ("docs" :> SwaggerUI) DefaultSwaggerSchemaEndpoint
 -- /extra/             — Swagger UI
 -- /extra/swagger.json — Swagger spec
 :<|> "extra" :> DefaultSwaggerSchemaUI
 :<|> API
```

**Comment by phadej** [comment]
Superseded by #12. Thanks anyhow for discussion opener!

**Pull request closed without merging**
