### PR TITLE
Updates 2016-12-20

### PR DESCRIPTION
**Pull request by phadej**
Ping @fizruk, if you want to try this first.

### CODE REVIEW

**Comment by fizruk** [comment]
Hmm... would Cabal flag make more sense here?
I mean, is it likely to want several UIs in an app?

Anyway, we should at least use custom type in place of `Bool`.

I'll be able to try the new UI out later.

**Comment by phadej** [comment]
cabal flag is problematic for e.g. Stackage

**Comment by phadej** [comment]
btw, the `Bool` is only in tests.

**Comment by fizruk** [comment]
@phadej ok, works for my API, except on the left pane the menu to select endpoints now is full of empty lines:
screen shot 2016-12-20 at 23 21 40

This is because we don't by default add endpoint descriptions in `servant-swagger`.
I think it might be a good idea to generate default descriptions... but that's `servant-swagger` issue.

Overall, this PR is great, let's have it! 👍

**Pull request merged**
